// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

/**
 * AuthMethod is the preferred authentication strategy for a Host.
 */
export enum AuthMethod {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AuthMethodAgent = "agent",
    AuthMethodIdentity = "identity",
    AuthMethodPassword = "password",
};

/**
 * Credential is a reusable login identity (user + auth method + identity files)
 * referenced by hosts. Its password, if any, lives in the Secret Service keyed
 * by credential ID — never in this database.
 */
export class Credential {
    "id": number;
    "name": string;
    "user": string;
    "authMethod": AuthMethod;
    "identityFiles": string[];
    "createdAt": string;
    "updatedAt": string;

    /** Creates a new Credential instance. */
    constructor($$source: Partial<Credential> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("user" in $$source)) {
            this["user"] = "";
        }
        if (!("authMethod" in $$source)) {
            this["authMethod"] = AuthMethod.$zero;
        }
        if (!("identityFiles" in $$source)) {
            this["identityFiles"] = [];
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Credential instance from a string or object.
     */
    static createFrom($$source: any = {}): Credential {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("identityFiles" in $$parsedSource) {
            $$parsedSource["identityFiles"] = $$createField4_0($$parsedSource["identityFiles"]);
        }
        return new Credential($$parsedSource as Partial<Credential>);
    }
}

/**
 * CredentialInput is the payload for creating/updating a Credential from the UI.
 */
export class CredentialInput {
    "name": string;
    "user": string;
    "authMethod": AuthMethod;
    "identityFiles": string[];

    /** Creates a new CredentialInput instance. */
    constructor($$source: Partial<CredentialInput> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("user" in $$source)) {
            this["user"] = "";
        }
        if (!("authMethod" in $$source)) {
            this["authMethod"] = AuthMethod.$zero;
        }
        if (!("identityFiles" in $$source)) {
            this["identityFiles"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CredentialInput instance from a string or object.
     */
    static createFrom($$source: any = {}): CredentialInput {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("identityFiles" in $$parsedSource) {
            $$parsedSource["identityFiles"] = $$createField3_0($$parsedSource["identityFiles"]);
        }
        return new CredentialInput($$parsedSource as Partial<CredentialInput>);
    }
}

/**
 * Folder groups hosts in the sidebar tree.
 */
export class Folder {
    "id": number;
    "name": string;
    "icon": string;
    "parentId"?: number | null;
    "sortOrder": number;

    /** Creates a new Folder instance. */
    constructor($$source: Partial<Folder> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("icon" in $$source)) {
            this["icon"] = "";
        }
        if (!("sortOrder" in $$source)) {
            this["sortOrder"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Folder instance from a string or object.
     */
    static createFrom($$source: any = {}): Folder {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Folder($$parsedSource as Partial<Folder>);
    }
}

/**
 * ForwardKind mirrors internal/forwarding.Kind but lives here so the storage
 * layer has no dependency on the engine. Values must stay in sync.
 */
export enum ForwardKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ForwardLocal = "local",
    ForwardRemote = "remote",
    ForwardDynamic = "dynamic",
};

/**
 * ForwardRule is a persisted port-forwarding definition scoped to one host.
 */
export class ForwardRule {
    "id": number;
    "hostId": number;
    "kind": ForwardKind;
    "label": string;
    "bindAddr": string;
    "bindPort": number;
    "destHost": string;
    "destPort": number;
    "autoStart": boolean;

    /** Creates a new ForwardRule instance. */
    constructor($$source: Partial<ForwardRule> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("hostId" in $$source)) {
            this["hostId"] = 0;
        }
        if (!("kind" in $$source)) {
            this["kind"] = ForwardKind.$zero;
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("bindAddr" in $$source)) {
            this["bindAddr"] = "";
        }
        if (!("bindPort" in $$source)) {
            this["bindPort"] = 0;
        }
        if (!("destHost" in $$source)) {
            this["destHost"] = "";
        }
        if (!("destPort" in $$source)) {
            this["destPort"] = 0;
        }
        if (!("autoStart" in $$source)) {
            this["autoStart"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ForwardRule instance from a string or object.
     */
    static createFrom($$source: any = {}): ForwardRule {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ForwardRule($$parsedSource as Partial<ForwardRule>);
    }
}

/**
 * ForwardRuleInput is the payload for creating/updating a rule.
 */
export class ForwardRuleInput {
    "hostId": number;
    "kind": ForwardKind;
    "label": string;
    "bindAddr": string;
    "bindPort": number;
    "destHost": string;
    "destPort": number;
    "autoStart": boolean;

    /** Creates a new ForwardRuleInput instance. */
    constructor($$source: Partial<ForwardRuleInput> = {}) {
        if (!("hostId" in $$source)) {
            this["hostId"] = 0;
        }
        if (!("kind" in $$source)) {
            this["kind"] = ForwardKind.$zero;
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("bindAddr" in $$source)) {
            this["bindAddr"] = "";
        }
        if (!("bindPort" in $$source)) {
            this["bindPort"] = 0;
        }
        if (!("destHost" in $$source)) {
            this["destHost"] = "";
        }
        if (!("destPort" in $$source)) {
            this["destPort"] = 0;
        }
        if (!("autoStart" in $$source)) {
            this["autoStart"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ForwardRuleInput instance from a string or object.
     */
    static createFrom($$source: any = {}): ForwardRuleInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ForwardRuleInput($$parsedSource as Partial<ForwardRuleInput>);
    }
}

/**
 * Host is a connection target as shown in the sidebar host list.
 */
export class Host {
    "id": number;
    "label": string;
    "hostname": string;
    "port": number;
    "user": string;
    "identityFiles": string[];
    "proxyJump": string;
    "forwardAgent": boolean;
    "authMethod": AuthMethod;
    "protocol": HostProtocol;
    "remotePath": string;
    "folderId"?: number | null;
    "credentialId"?: number | null;
    "favorite": boolean;
    "source": HostSource;
    "notes": string;
    "loginScript": string;
    "controlPanelUrl": string;
    "tags": string[];
    "sortOrder": number;
    "lastUsedAt"?: string | null;
    "createdAt": string;
    "updatedAt": string;

    /** Creates a new Host instance. */
    constructor($$source: Partial<Host> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("hostname" in $$source)) {
            this["hostname"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("user" in $$source)) {
            this["user"] = "";
        }
        if (!("identityFiles" in $$source)) {
            this["identityFiles"] = [];
        }
        if (!("proxyJump" in $$source)) {
            this["proxyJump"] = "";
        }
        if (!("forwardAgent" in $$source)) {
            this["forwardAgent"] = false;
        }
        if (!("authMethod" in $$source)) {
            this["authMethod"] = AuthMethod.$zero;
        }
        if (!("protocol" in $$source)) {
            this["protocol"] = HostProtocol.$zero;
        }
        if (!("remotePath" in $$source)) {
            this["remotePath"] = "";
        }
        if (!("favorite" in $$source)) {
            this["favorite"] = false;
        }
        if (!("source" in $$source)) {
            this["source"] = HostSource.$zero;
        }
        if (!("notes" in $$source)) {
            this["notes"] = "";
        }
        if (!("loginScript" in $$source)) {
            this["loginScript"] = "";
        }
        if (!("controlPanelUrl" in $$source)) {
            this["controlPanelUrl"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }
        if (!("sortOrder" in $$source)) {
            this["sortOrder"] = 0;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Host instance from a string or object.
     */
    static createFrom($$source: any = {}): Host {
        const $$createField5_0 = $$createType0;
        const $$createField18_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("identityFiles" in $$parsedSource) {
            $$parsedSource["identityFiles"] = $$createField5_0($$parsedSource["identityFiles"]);
        }
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField18_0($$parsedSource["tags"]);
        }
        return new Host($$parsedSource as Partial<Host>);
    }
}

/**
 * HostInput is the payload for creating/updating a Host from the UI.
 */
export class HostInput {
    "label": string;
    "hostname": string;
    "port": number;
    "user": string;
    "identityFiles": string[];
    "proxyJump": string;
    "forwardAgent": boolean;
    "authMethod": AuthMethod;
    "protocol": HostProtocol;
    "remotePath": string;
    "folderId"?: number | null;

    /**
     * CredentialID, when set, makes the host inherit user/auth/identity files
     * from a shared credential; the inline fields above are then ignored.
     */
    "credentialId"?: number | null;
    "notes": string;
    "loginScript": string;
    "controlPanelUrl": string;
    "tags": string[];

    /** Creates a new HostInput instance. */
    constructor($$source: Partial<HostInput> = {}) {
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("hostname" in $$source)) {
            this["hostname"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("user" in $$source)) {
            this["user"] = "";
        }
        if (!("identityFiles" in $$source)) {
            this["identityFiles"] = [];
        }
        if (!("proxyJump" in $$source)) {
            this["proxyJump"] = "";
        }
        if (!("forwardAgent" in $$source)) {
            this["forwardAgent"] = false;
        }
        if (!("authMethod" in $$source)) {
            this["authMethod"] = AuthMethod.$zero;
        }
        if (!("protocol" in $$source)) {
            this["protocol"] = HostProtocol.$zero;
        }
        if (!("remotePath" in $$source)) {
            this["remotePath"] = "";
        }
        if (!("notes" in $$source)) {
            this["notes"] = "";
        }
        if (!("loginScript" in $$source)) {
            this["loginScript"] = "";
        }
        if (!("controlPanelUrl" in $$source)) {
            this["controlPanelUrl"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HostInput instance from a string or object.
     */
    static createFrom($$source: any = {}): HostInput {
        const $$createField4_0 = $$createType0;
        const $$createField15_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("identityFiles" in $$parsedSource) {
            $$parsedSource["identityFiles"] = $$createField4_0($$parsedSource["identityFiles"]);
        }
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField15_0($$parsedSource["tags"]);
        }
        return new HostInput($$parsedSource as Partial<HostInput>);
    }
}

/**
 * HostProtocol controls which native workspace is opened after the SSH
 * transport has authenticated.
 */
export enum HostProtocol {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    HostProtocolSSH = "ssh",
    HostProtocolSFTP = "sftp",

    /**
     * HostProtocolWeb is a host whose "connection" is a web control panel opened
     * as an embedded browser tab (ControlPanelURL), not an SSH transport.
     */
    HostProtocolWeb = "web",
};

/**
 * HostSource records where a Host definition came from.
 */
export enum HostSource {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    HostSourceManual = "manual",
    HostSourceSSHConfig = "ssh_config",
};

/**
 * Snippet is a reusable command. HostID is nil for a global snippet.
 */
export class Snippet {
    "id": number;
    "name": string;
    "command": string;
    "hostId"?: number | null;

    /** Creates a new Snippet instance. */
    constructor($$source: Partial<Snippet> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("command" in $$source)) {
            this["command"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Snippet instance from a string or object.
     */
    static createFrom($$source: any = {}): Snippet {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Snippet($$parsedSource as Partial<Snippet>);
    }
}

/**
 * SnippetInput is the payload for creating/updating a snippet.
 */
export class SnippetInput {
    "name": string;
    "command": string;
    "hostId"?: number | null;

    /** Creates a new SnippetInput instance. */
    constructor($$source: Partial<SnippetInput> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("command" in $$source)) {
            this["command"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SnippetInput instance from a string or object.
     */
    static createFrom($$source: any = {}): SnippetInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SnippetInput($$parsedSource as Partial<SnippetInput>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
