// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

/**
 * Listener is one TCP socket the host accepts connections on.
 */
export class Listener {
    /**
     * Address is the bind address as reported by the remote tool: a literal
     * IP, or "*" for a wildcard bind.
     */
    "address": string;
    "port": number;

    /**
     * Process is the program holding the socket, empty when the remote tool
     * could not attribute it (which is the normal case for other users'
     * sockets without root).
     */
    "process": string;
    "pid"?: number;

    /**
     * Loopback marks a socket reachable only from the host itself — the case
     * where a forward is not a convenience but the only way in.
     */
    "loopback": boolean;

    /**
     * Service is the best name we could establish for what is behind the port.
     */
    "service": string;

    /**
     * Detail is the evidence Service was drawn from — a container image or the
     * process command line — so a wrong guess is visibly a guess.
     */
    "detail": string;

    /**
     * Container is the container publishing this port, when one does.
     */
    "container": string;

    /**
     * Origin records how Service was established: "container", "process" or
     * "port". Only the last one is guesswork.
     */
    "origin": string;

    /**
     * Scheme is "http" or "https" when this looks like a web interface worth
     * opening as a panel, and empty otherwise.
     */
    "scheme": string;

    /** Creates a new Listener instance. */
    constructor($$source: Partial<Listener> = {}) {
        if (!("address" in $$source)) {
            this["address"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("process" in $$source)) {
            this["process"] = "";
        }
        if (!("loopback" in $$source)) {
            this["loopback"] = false;
        }
        if (!("service" in $$source)) {
            this["service"] = "";
        }
        if (!("detail" in $$source)) {
            this["detail"] = "";
        }
        if (!("container" in $$source)) {
            this["container"] = "";
        }
        if (!("origin" in $$source)) {
            this["origin"] = "";
        }
        if (!("scheme" in $$source)) {
            this["scheme"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Listener instance from a string or object.
     */
    static createFrom($$source: any = {}): Listener {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Listener($$parsedSource as Partial<Listener>);
    }
}
