// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sftp$0 from "../sftp/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as storage$0 from "../storage/models.js";

/**
 * ActiveForward describes a running forward for the frontend.
 */
export class ActiveForward {
    "ruleId": number;
    "kind": string;
    "label": string;
    "boundAddr": string;

    /** Creates a new ActiveForward instance. */
    constructor($$source: Partial<ActiveForward> = {}) {
        if (!("ruleId" in $$source)) {
            this["ruleId"] = 0;
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("boundAddr" in $$source)) {
            this["boundAddr"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ActiveForward instance from a string or object.
     */
    static createFrom($$source: any = {}): ActiveForward {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ActiveForward($$parsedSource as Partial<ActiveForward>);
    }
}

/**
 * ConnectionInfo is returned to the frontend after Connect/Reconnect and
 * describes the connection plus its initial terminal tab.
 */
export class ConnectionInfo {
    "connectionId": string;
    "hostId": number;
    "hostLabel": string;
    "status": ConnectionStatus;
    "serverVersion"?: string;
    "authMethod"?: string;
    "protocol": storage$0.HostProtocol;
    "initialTabId": string;
    "initialTabKind": TabKind;
    "error"?: string;

    /**
     * Warning carries a non-fatal notice about an otherwise successful
     * connection (e.g. agent forwarding was requested but unavailable).
     */
    "warning"?: string;

    /** Creates a new ConnectionInfo instance. */
    constructor($$source: Partial<ConnectionInfo> = {}) {
        if (!("connectionId" in $$source)) {
            this["connectionId"] = "";
        }
        if (!("hostId" in $$source)) {
            this["hostId"] = 0;
        }
        if (!("hostLabel" in $$source)) {
            this["hostLabel"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = ConnectionStatus.$zero;
        }
        if (!("protocol" in $$source)) {
            this["protocol"] = storage$0.HostProtocol.$zero;
        }
        if (!("initialTabId" in $$source)) {
            this["initialTabId"] = "";
        }
        if (!("initialTabKind" in $$source)) {
            this["initialTabKind"] = TabKind.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectionInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ConnectionInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConnectionInfo($$parsedSource as Partial<ConnectionInfo>);
    }
}

/**
 * ConnectionStatus mirrors the lifecycle shown in the status bar and tab header.
 */
export enum ConnectionStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StatusConnecting = "connecting",
    StatusConnected = "connected",
    StatusDisconnected = "disconnected",
    StatusError = "error",
};

/**
 * ImportResult summarizes an ~/.ssh/config import run.
 */
export class ImportResult {
    "importedCount": number;
    "hosts": storage$0.Host[];

    /** Creates a new ImportResult instance. */
    constructor($$source: Partial<ImportResult> = {}) {
        if (!("importedCount" in $$source)) {
            this["importedCount"] = 0;
        }
        if (!("hosts" in $$source)) {
            this["hosts"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ImportResult {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("hosts" in $$parsedSource) {
            $$parsedSource["hosts"] = $$createField1_0($$parsedSource["hosts"]);
        }
        return new ImportResult($$parsedSource as Partial<ImportResult>);
    }
}

/**
 * SFTPDirectory is one directory snapshot plus its canonical remote path.
 */
export class SFTPDirectory {
    "path": string;
    "entries": sftp$0.Entry[];

    /** Creates a new SFTPDirectory instance. */
    constructor($$source: Partial<SFTPDirectory> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("entries" in $$source)) {
            this["entries"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SFTPDirectory instance from a string or object.
     */
    static createFrom($$source: any = {}): SFTPDirectory {
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entries" in $$parsedSource) {
            $$parsedSource["entries"] = $$createField1_0($$parsedSource["entries"]);
        }
        return new SFTPDirectory($$parsedSource as Partial<SFTPDirectory>);
    }
}

/**
 * SettingResult is a single key's value from the settings table.
 */
export class SettingResult {
    "value": string;
    "exists": boolean;

    /** Creates a new SettingResult instance. */
    constructor($$source: Partial<SettingResult> = {}) {
        if (!("value" in $$source)) {
            this["value"] = "";
        }
        if (!("exists" in $$source)) {
            this["exists"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SettingResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SettingResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SettingResult($$parsedSource as Partial<SettingResult>);
    }
}

/**
 * TabInfo describes one terminal tab.
 */
export class TabInfo {
    "tabId": string;
    "connectionId": string;
    "title": string;
    "kind": TabKind;

    /** Creates a new TabInfo instance. */
    constructor($$source: Partial<TabInfo> = {}) {
        if (!("tabId" in $$source)) {
            this["tabId"] = "";
        }
        if (!("connectionId" in $$source)) {
            this["connectionId"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = TabKind.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TabInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): TabInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TabInfo($$parsedSource as Partial<TabInfo>);
    }
}

/**
 * TabKind tells the frontend which native workspace belongs in a tab.
 */
export enum TabKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    TabKindTerminal = "terminal",
    TabKindSFTP = "sftp",
};

/**
 * TransferRequest is the payload from the frontend to start an rsync transfer.
 */
export class TransferRequest {
    "hostId": number;
    "localPath": string;
    "remotePath": string;
    "upload": boolean;
    "archive": boolean;
    "compress": boolean;
    "delete": boolean;
    "dryRun": boolean;

    /** Creates a new TransferRequest instance. */
    constructor($$source: Partial<TransferRequest> = {}) {
        if (!("hostId" in $$source)) {
            this["hostId"] = 0;
        }
        if (!("localPath" in $$source)) {
            this["localPath"] = "";
        }
        if (!("remotePath" in $$source)) {
            this["remotePath"] = "";
        }
        if (!("upload" in $$source)) {
            this["upload"] = false;
        }
        if (!("archive" in $$source)) {
            this["archive"] = false;
        }
        if (!("compress" in $$source)) {
            this["compress"] = false;
        }
        if (!("delete" in $$source)) {
            this["delete"] = false;
        }
        if (!("dryRun" in $$source)) {
            this["dryRun"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TransferRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): TransferRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TransferRequest($$parsedSource as Partial<TransferRequest>);
    }
}

// Private type creation functions
const $$createType0 = storage$0.Host.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = sftp$0.Entry.createFrom;
const $$createType3 = $Create.Array($$createType2);
